### ISSUE TITLE
[Feature]: 프로젝트 초기 설정하기

### ISSUE THREAD

**Issue by wontory** [9oormthon-univ/2024_DANPOONG_TEAM_23_FE#1]
### Describe

Vite로 리액트 프로젝트를 생성합니다.

### Tasks

- [x] create vite app
  - [x] set up **TypeScript**
  - [x] set up **SWC**
- [x] set up **Husky**
  - [x] set up **commitlint**
  - [x] set up **lint-staged**
- [x] set up **Prettier**
- [x] set up **ESLint**
- [x] set up **Tailwind CSS**
- [x] set up **react-router-dom**
- [x] set up project folder structure
- [x] edit README.md
