### ISSUE TITLE
[Feature]: 진단 페이지 퍼블리싱하기

### ISSUE THREAD

**Issue by devwontory** [9oormthon-univ/2024_DANPOONG_TEAM_23_FE#10]
### Describe

- 건강일지를 작성하는 부분을 퍼블리싱합니다.
- 부위 선택부터 질문 셋, 이후 AI 생성 질문까지 고려해 프로세스를 완성합니다.
- use-funnel을 사용해 구현합니다.

### Tasks

- [x] 부위 선택 버튼 만들기
- [x] 부위 선택 페이지 퍼블리싱
- [x] 세부 부위 선택 페이지 퍼블리싱
- [x] 질문 + 토글 셋 페이지 퍼블리싱(AI 질문에서 재사용하기 위해 유동적인 데이터 구조 가져가기)
- [x] 함께 나타나는 증상 선택 페이지 퍼블리싱
- [ ] 스플래쉬 화면

**Comment by devwontory** [comment]
남은 작업은 후순위로 잡고 해당 이슈에서 분기처리하여 관리합니다.
- related #14
