### ISSUE TITLE
[Feature]: 진단 결과 페이지 퍼블리싱하기

### ISSUE THREAD

**Issue by devwontory** [9oormthon-univ/2024_DANPOONG_TEAM_23_FE#11]
### Describe

- 진단과 추천 병원을 포함하는 진단 결과 페이지를 퍼블리싱합니다.
- 진단 결과는 Kakao Map으로 위치를 표시하는 기능을 포함합니다.

### Tasks

- [x] 진단 결과 페이지 퍼블리싱
  - [x] 마크다운 파싱하기
- [x] 병원 알아보기 페이지 퍼블리싱
  - [x] 카카오 지도로 병원 위치 표시하기
