### ISSUE TITLE
[Feature]: Auth API 연결하기

### ISSUE THREAD

**Issue by devwontory** [9oormthon-univ/2024_DANPOONG_TEAM_23_FE#22]
### Describe

Auth API를 연결하고, Auth 유무로 라우팅을 제어합니다.

### Tasks

- [ ] Auth API 연결
- [x] Axios instance 생성
- [x] Authorized Route와 Unauthorized Route 구별하기
