### ISSUE TITLE
[Feature]: QA 디자인 수정

### ISSUE THREAD

**Issue by devjaeyoon** [9oormthon-univ/2024_DANPOONG_TEAM_23_FE#25]
### Describe

서비스의 페이지 UI 디자인을 수정합니다.

### Tasks

- [x] 메인페이지 버튼 텍스트 자간 수정
- [x] 메인 페이지 컨텐츠 잘리는거 수정
- [x] 회원탈퇴 모달 '동의합니다' 텍스트 버튼화
- [x] 버튼 Stroke 제거 및 진단하러 가기 버튼만 Stroke화
- [x] 헤더 컴포넌트 border-gray50 오타 수정
- [x] 온보딩 페이지 핸드폰 이미지 하단으로 이동
- [x] 온보딩 페이지 indicator와 핸드폰 이미지 사이 간격 추가
- [x] SelectGender GenderToggle z-index 추가
