### ISSUE TITLE
[Feature]: API handler 추가하기

### ISSUE THREAD

**Issue by devwontory** [9oormthon-univ/2024_DANPOONG_TEAM_23_FE#34]
### Describe

API 명세 사항을 axios로 추가합니다.

### Tasks

- 회원 API
  - [x] 회원탈퇴
  - [x] 회원 로그아웃
- 증상 진단
  - [x] 채팅 시작
  - [x] 채팅 계속하기
  - [x] AI 진단결과 재조회
  - [x] 추천병원 간략 조회
  - [x] 추천병원 상세 조회
- 건강일지
  - [x] 오늘의 건강 기록 조회
  - [x] 내 건강 변화 조회
  - [x] 진단 기록 월별 전체 조회
  - [x] 내 건강 변화 상세 조회 
- [x] 응답 타입 추가하기
