### ISSUE TITLE
[Feature]: 프로젝트 SVG 설정하기

### ISSUE THREAD

**Issue by devjaeyoon** [9oormthon-univ/2024_DANPOONG_TEAM_23_FE#4]
### Describe

* vite-plugin-svgr 플러그인 설치 및 적용
* SVG 파일 React 컴포넌트화 및 타입 정의

### Tasks

- [x] vite-plugin-svgr 플러그인 설치
- [x] vite-plugin-svgr 플러그인 적용
- [x] SVG React Component 커스텀 타입 정의
